### ISSUE TITLE
Support for Multiple Accounts

### ISSUE THREAD

**Issue by fabrobinet** [nomad/cupertino#171]
Would it be possible to reuse login credentials and switch at login from one account to another ?

My use case is I'd like to write a script that download a provisioning profile on one account then switch to another account and download another provisioning profile... 
It doesn't seem that I can do this at the moment, can you confirm ? 

Thanks for your help and the awesome work you guys are doing !

**Comment by BenWaller** [comment]
I'm attempting to follow this workaround in order to logout and then login with different credentials, but would like to send in those credentials programmatically instead of manually typing them in terminal. Would it be possible to support this functionality? Or is there a way for me to input them in a bash script and not have to change the cupertino code?
