### ISSUE TITLE
feature request: allow me to name the provisioning profile I download

### ISSUE THREAD

**Issue by ronkorving** [nomad/cupertino#198]
In automation, I don't want to have to guess for filenames (and translate special characters etc) or extract it from what is meant to be human readable output. Any chance I could pass a filename or catch its contents from stdout?

**Comment by KrauseFx** [comment]
As far as I know, that's not possible, but you can take a look at the source: https://github.com/nomad/cupertino/blob/master/lib/cupertino/provisioning_portal/commands/profiles.rb#L61
It would be easy to update `cupertino` to support custom file names.

If you want, you can also use [sigh](https://github.com/krausefx/sigh) to do that:

```
sigh -f 'filename.mobileprovision'
```

and specify the output path:

```
sigh -f 'filename.mobileprovision' -o './profiles'
```

**Comment by irons** [comment]
I'd consider it a bad idea to rename provisioning profiles anywhere except the dev portal. There's machinery in xcodebuild that expects to be passed the name of the profile as it was originally specified, that is, using `-exportProvisioningProfile "My Amazing Profile"` to match `My_Amazing_Profile.mobileprovision`. Changing the profile name on disk increases the opportunity to assume the wrong internal profile name, and remain confused about why xcodebuild can't find it.

**Comment by KrauseFx** [comment]
Usually you define the provisioning profile either by its UDID or by giving `xcodebuild` the path to the provisioning profile to use.

**Comment by irons** [comment]
Xcode will accept provisioning profile UUIDs in build settings or xcconfigs, though I'm not aware of circumstances in which it'll accept a full path. Neither of those approaches works in my `xcodebuild -exportArchive` example, where the only accepted profile specifier is its full name, as entered on the dev portal. (I just doublechecked, albeit with xcodebuild 6.2.)

**Comment by ronkorving** [comment]
I'm actually using the UUID, because that's how OS X will install it for you. Basically, in my automated setup I'm saving it in a temporary empty directory, so it becomes the only file there (again, I don't want to guess the filename). But it would be nice if I could simply call it "my.mobileprofile" (a predictable, meaningless name), extract the UUID, then move it into it's right place and give it the right name (UUID.mobileprofile).

**Comment by irons** [comment]
I guess this is a disagreement about what should be considered "the right name". I don't allow any auto-generated provisioning profiles on the build servers I run, because we expect the profile in the repo to take precedence when building. 

To do that, we copy profiles from the repo into `~/Library/MobileDevice/Provisioning Profiles` before xcodebuild starts. That depends on profiles' filenames staying consistent, so they can be reliably overwritten. If I see a profile with a UUID-style filename on a build machine, someone screwed up.

For this reason, and because of the `exportArchive` edge case I mentioned above, I'd recommend against treating profile names as editable information. We use Xcode's automatic profile management for development, but for a build server, it's not consistent or predictable enough to tolerate.

**Comment by sfransen** [comment]
I agree never let Xcode touch the portal
I never has a account setup in Xcode preferences
