### ISSUE TITLE
Connection to developer.apple.com refused

### ISSUE THREAD

**Issue by c1rd3c** [nomad/cupertino#226]
Hi,

I have been having issues using ios since Wednesday September 9 (the day of the apple conference). When trying to fetch ios profiles, I get a connection issue. Has anyone noticed the same?

ios profiles
error: connection refused: developer.apple.com:443.

Thanks,
Cédric

**Comment by sfransen** [comment]
Did you log on with team agent account and accept the new terms

Sent from my iPhone5

On Sep 11, 2015, at 9:55 AM, c1rd3c <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I have been having issues using ios since Wednesday September 9 (the day of the apple conference). When trying to fetch ios profiles, I get a connection issue. Has anyone noticed the same?

ios profiles
error: connection refused: developer.apple.com<http://developer.apple.com>:443.

Thanks,
Cédric

**Comment by c1rd3c** [comment]
Yes, the team agent has accepted the the new terms and condition, but I still can't fetch profiles.

**Comment by sfransen** [comment]
This work fine for me

Make sure the user also did the terms too if needed
